# Generated by Django 5.1.15 on 2026-10-09 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=120)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_concierge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation avec le Concierge',
                'ordering': ['-mis_a_jour_le'],
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Voyageur'), ('assistant', 'Concierge')], max_length=10)),
                ('contenu', models.JSONField(help_text="Blocs de contenu de l'API Claude")),
                ('texte', models.TextField(blank=True)),
                ('cartes', models.JSONField(blank=True, default=list)),
                ('visible', models.BooleanField(default=True)),
                ('tokens_entree', models.PositiveIntegerField(default=0)),
                ('tokens_sortie', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='concierge.conversationmodel')),
            ],
            options={
                'ordering': ['cree_le', 'id'],
            },
        ),
    ]
