# Generated by Django 5.1.15 on 2026-10-09 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_reservationmodel_annule_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AeroportModel',
            fields=[
                ('code', models.CharField(help_text='Code IATA, par ex. LFW', max_length=3, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=2)),
                ('fuseau', models.CharField(help_text='Fuseau horaire, par ex. Africa/Lome', max_length=40)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aéroport',
                'ordering': ['ville'],
            },
        ),
        migrations.CreateModel(
            name='ChauffeurModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=60)),
                ('telephone', models.CharField(help_text="Avec l'indicatif, par ex. +228 90 00 00 00", max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Facultatif : reçoit le détail des courses attribuées', max_length=254)),
                ('categorie', models.CharField(choices=[('berline', 'Berline'), ('confort', 'SUV confort'), ('van', 'Minibus')], max_length=20)),
                ('vehicule', models.CharField(help_text='Marque, modèle et couleur', max_length=120)),
                ('immatriculation', models.CharField(max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('pays_versement', models.CharField(choices=[('TG', 'Togo'), ('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('NE', 'Niger'), ('ML', 'Mali')], max_length=2)),
                ('operateur_versement', models.CharField(choices=[('moov_tg', 'Moov Money (Flooz)'), ('togocel', 'Mixx by Yas (T-Money)'), ('mtn_open', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('sbin', 'Celtiis Cash'), ('orange_bf', 'Orange Money'), ('moov_bf', 'Moov Money'), ('airtel_ne', 'Airtel Money'), ('orange_ml', 'Orange Money'), ('moov_ml', 'Moov Money')], max_length=30)),
                ('numero_versement', models.CharField(help_text="Sans l'indicatif", max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('aeroports', models.ManyToManyField(related_name='chauffeurs', to='transferts.aeroportmodel')),
            ],
            options={
                'verbose_name': 'Chauffeur partenaire',
                'verbose_name_plural': 'Chauffeurs partenaires',
                'ordering': ['prenom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TransfertModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrivee', models.DateTimeField(help_text="Heure d'atterrissage prévue")),
                ('numero_vol', models.CharField(max_length=10)),
                ('passagers', models.PositiveSmallIntegerField()),
                ('bagages', models.PositiveSmallIntegerField()),
                ('categorie', models.CharField(choices=[('berline', 'Berline'), ('confort', 'SUV confort'), ('van', 'Minibus')], max_length=20)),
                ('destination', models.CharField(help_text='Adresse de dépose', max_length=255)),
                ('telephone', models.CharField(help_text="Numéro du voyageur, joignable à l'arrivée (WhatsApp)", max_length=20)),
                ('message', models.TextField(blank=True)),
                ('prix', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField()),
                ('majoration_nuit', models.BooleanField(default=False)),
                ('moyen', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('paypal', 'PayPal')], default='mobile_money', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('confirme', 'Payé, chauffeur à attribuer'), ('chauffeur_assigne', 'Chauffeur attribué'), ('termine', 'Effectué'), ('annule', 'Annulé')], default='en_attente_paiement', max_length=20)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('annule_par', models.CharField(blank=True, choices=[('voyageur', 'Voyageur'), ('plateforme', 'AfriStay'), ('expiration', 'Paiement non effectué à temps')], max_length=20)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('confirmation_notifiee', models.BooleanField(default=False, help_text='Paiement confirmé au voyageur')),
                ('admins_notifies', models.BooleanField(default=False, help_text='Administrateurs prévenus : chauffeur à attribuer')),
                ('alerte_sans_chauffeur', models.BooleanField(default=False, help_text='Alerte : arrivée dans moins de 24 h sans chauffeur')),
                ('chauffeur_notifie', models.BooleanField(default=False, help_text='Coordonnées du chauffeur envoyées au voyageur')),
                ('course_envoyee_chauffeur', models.BooleanField(default=False, help_text='Détail de la course envoyé au chauffeur')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='transferts.aeroportmodel')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='transferts.chauffeurmodel')),
                ('reservation', models.ForeignKey(blank=True, help_text='Séjour AfriStay associé (facultatif)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts', to='reservations.reservationmodel')),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert aéroport',
                'verbose_name_plural': 'Transferts aéroport',
                'ordering': ['-arrivee'],
            },
        ),
        migrations.CreateModel(
            name='VersementChauffeurModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_brut', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField()),
                ('montant', models.PositiveIntegerField()),
                ('date_prevue', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('envoye', 'Envoyé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('payout_id', models.CharField(blank=True, max_length=64)),
                ('mode', models.CharField(blank=True, max_length=30)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('notifie', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versements', to='transferts.chauffeurmodel')),
                ('transfert', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='versement', to='transferts.transfertmodel')),
            ],
            options={
                'verbose_name': 'Versement à un chauffeur',
                'verbose_name_plural': 'Versements aux chauffeurs',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='TarifTransfertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('berline', 'Berline'), ('confort', 'SUV confort'), ('van', 'Minibus')], max_length=20)),
                ('prix', models.PositiveIntegerField(help_text='En FCFA, hors majoration de nuit')),
                ('actif', models.BooleanField(default=True)),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='transferts.aeroportmodel')),
            ],
            options={
                'verbose_name': 'Tarif',
                'constraints': [models.UniqueConstraint(fields=('aeroport', 'categorie'), name='tarif_unique_par_categorie')],
            },
        ),
    ]
