import type { Property, Destination, Activity, Conversation, Booking } from "@/types";

export const destinations: Destination[] = [
  { id: "1", name: "Lomé", country: "Togo", count: 120, color: "#27AE60" },
  { id: "2", name: "Accra", country: "Ghana", count: 98, color: "#E67E22" },
  { id: "3", name: "Abidjan", country: "Côte d'Ivoire", count: 145, color: "#C0392B" },
  { id: "4", name: "Marrakech", country: "Maroc", count: 210, color: "#F39C12" },
];

export const properties: Property[] = [
  {
    id: "1",
    name: "Villa Sunset Beach",
    location: "Baguida",
    city: "Lomé",
    country: "Togo",
    price: 85,
    rating: 4.9,
    reviews: 87,
    type: "villa",
    amenities: ["piscine", "wifi", "clim", "parking"],
    images: [],
    description:
      "Magnifique villa avec vue imprenable sur l'océan Atlantique. 3 chambres, salon spacieux, cuisine équipée. Idéale pour des vacances en famille ou entre amis. La piscine chauffée à 28°C est disponible toute l'année.",
    isFavorite: false,
  },
  {
    id: "2",
    name: "Appartement Akwa Palace",
    location: "Akwa",
    city: "Douala",
    country: "Cameroun",
    price: 55,
    rating: 4.6,
    reviews: 124,
    type: "appartement",
    amenities: ["wifi", "clim", "parking"],
    images: [],
    description:
      "Appartement moderne en plein cœur du quartier Akwa. Accès facile aux restaurants et commerces. Vue panoramique sur la ville.",
    isFavorite: true,
  },
  {
    id: "3",
    name: "Hôtel du Plateau",
    location: "Le Plateau",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    price: 120,
    rating: 4.8,
    reviews: 203,
    type: "hotel",
    amenities: ["piscine", "wifi", "clim", "parking", "spa", "gym"],
    images: [],
    description:
      "Hôtel 4 étoiles situé dans le quartier des affaires. Service premium, spa et restaurant gastronomique.",
    isFavorite: false,
  },
  {
    id: "4",
    name: "Riad Médina",
    location: "Médina",
    city: "Marrakech",
    country: "Maroc",
    price: 95,
    rating: 4.7,
    reviews: 156,
    type: "villa",
    amenities: ["piscine", "wifi", "jardin"],
    images: [],
    description:
      "Authentique riad marocain avec patio central et fontaine. Architecture traditionnelle revisitée avec tout le confort moderne.",
    isFavorite: false,
  },
];

export const activities: Activity[] = [
  {
    id: "1",
    name: "Plage de Lomé",
    category: "activite",
    city: "Lomé",
    country: "Togo",
    rating: 4.5,
    price: null,
    description: "La plus longue plage urbaine d'Afrique de l'Ouest",
    tags: ["Détente", "Baignade"],
  },
  {
    id: "2",
    name: "Musée National",
    category: "site",
    city: "Lomé",
    country: "Togo",
    rating: 4.2,
    price: 5,
    description: "Découvrez l'histoire et la culture togolaise",
    tags: ["Culture", "Histoire"],
  },
  {
    id: "3",
    name: "Lac Togo",
    category: "activite",
    city: "Lomé",
    country: "Togo",
    rating: 4.8,
    price: 15,
    description: "Excursion en pirogue sur le lac",
    tags: ["Excursion", "Nature"],
  },
  {
    id: "4",
    name: "Forêt de Missahoe",
    category: "activite",
    city: "Kpalimé",
    country: "Togo",
    rating: 4.6,
    price: 10,
    description: "Randonnée dans la forêt tropicale",
    tags: ["Nature", "Randonnée"],
  },
  {
    id: "5",
    name: "Restaurant La Terrasse",
    category: "restaurant",
    city: "Lomé",
    country: "Togo",
    rating: 4.4,
    price: 25,
    description: "Cuisine africaine raffinée avec vue sur la mer",
    tags: ["Gastronomie", "Vue mer"],
  },
];

export const conversations: Conversation[] = [
  {
    id: "1",
    propertyId: "1",
    propertyName: "Villa Sunset Beach",
    hostName: "Kofi Mensah",
    isOnline: true,
    lastMessage: "Oui, elle est chauffée à 28°C toute l'année.",
    lastMessageAt: "2025-01-10T14:30:00",
    messages: [
      {
        id: "1",
        senderId: "host",
        senderName: "Kofi Mensah",
        content: "Bonjour ! Comment puis-je vous aider ?",
        createdAt: "2025-01-10T14:00:00",
        isOwn: false,
      },
      {
        id: "2",
        senderId: "me",
        senderName: "Moi",
        content: "Bonjour, la piscine est-elle chauffée ?",
        createdAt: "2025-01-10T14:15:00",
        isOwn: true,
      },
      {
        id: "3",
        senderId: "host",
        senderName: "Kofi Mensah",
        content: "Oui, elle est chauffée à 28°C toute l'année.",
        createdAt: "2025-01-10T14:30:00",
        isOwn: false,
      },
      {
        id: "4",
        senderId: "me",
        senderName: "Moi",
        content: "Parfait, merci !",
        createdAt: "2025-01-10T14:31:00",
        isOwn: true,
      },
    ],
  },
];

export const mockBooking: Booking = {
  id: "1",
  property: properties[0],
  checkIn: "2025-01-15",
  checkOut: "2025-01-20",
  guests: 2,
  nights: 5,
  pricePerNight: 85,
  serviceFee: 34,
  totalPrice: 459,
  paymentMethod: "mobile_money",
  status: "pending",
};
