# Generated by Django 5.1.15 on 2026-10-10 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Adresse de la page : /give/<slug>', max_length=80, unique=True)),
                ('cause', models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('eau', "Accès à l'eau"), ('environnement', 'Environnement')], max_length=20)),
                ('pays', models.CharField(choices=[('TG', 'Togo'), ('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('NE', 'Niger'), ('ML', 'Mali')], max_length=2)),
                ('ville', models.CharField(max_length=100)),
                ('resume', models.CharField(help_text="Une phrase affichée sur la carte de l'ONG", max_length=200)),
                ('description', models.TextField(help_text='Mission, actions menées, résultats')),
                ('logo', models.ImageField(blank=True, upload_to='give/logos/')),
                ('image', models.ImageField(blank=True, help_text='Photo de couverture', upload_to='give/images/')),
                ('site_web', models.URLField(blank=True)),
                ('numero_enregistrement', models.CharField(help_text="Numéro de récépissé ou d'enregistrement officiel (affiché publiquement)", max_length=80)),
                ('verifiee_le', models.DateField(blank=True, help_text='Date de la vérification ; vide = non publiée', null=True)),
                ('verification', models.TextField(blank=True, help_text='Ce qui a été vérifié (affiché publiquement) : récépissé, statuts, compte bancaire, visite…')),
                ('contact_nom', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('coordonnees_reversement', models.TextField(blank=True, help_text="IBAN / RIB ou compte Mobile Money au nom de l'ONG (jamais affiché sur le site)")),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ONG partenaire',
                'verbose_name_plural': 'ONG partenaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProjetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('cause', models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('eau', "Accès à l'eau"), ('environnement', 'Environnement')], max_length=20)),
                ('resume', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=120)),
                ('objectif', models.PositiveIntegerField(blank=True, help_text='Montant à réunir en FCFA (facultatif)', null=True)),
                ('image', models.ImageField(blank=True, upload_to='give/projets/')),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='give.organisationmodel')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ReversementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.DateField(help_text='Premier jour du mois des dons reversés')),
                ('montant', models.PositiveIntegerField(default=0, help_text="Total reversé à l'ONG en FCFA")),
                ('nb_dons', models.PositiveIntegerField(default=0)),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('a_effectuer', 'À effectuer'), ('effectue', 'Effectué')], default='a_effectuer', max_length=20)),
                ('moyen', models.CharField(blank=True, choices=[('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('reference_operation', models.CharField(blank=True, help_text='Référence du virement', max_length=80)),
                ('justificatif', models.FileField(blank=True, help_text="Preuve du virement (PDF ou image), publiée sur la page de l'ONG : masquer les numéros de compte", upload_to='give/justificatifs/')),
                ('note', models.TextField(blank=True, help_text="Message public (ce que l'ONG a fait des fonds, par exemple)")),
                ('effectue_le', models.DateField(blank=True, null=True)),
                ('admins_notifies', models.BooleanField(default=False, help_text='Équipe prévenue : reversement à effectuer')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversements', to='give.organisationmodel')),
            ],
            options={
                'verbose_name': 'Reversement à une ONG',
                'verbose_name_plural': 'Reversements aux ONG',
                'ordering': ['-periode', 'organisation__nom'],
            },
        ),
        migrations.CreateModel(
            name='DonModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(help_text='Montant choisi par le donateur')),
                ('couvre_frais', models.BooleanField(default=True, help_text='Le donateur ajoute les frais de paiement à son don')),
                ('frais', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField(help_text='Montant débité')),
                ('montant_ong', models.PositiveIntegerField(help_text="Montant reversé à l'ONG")),
                ('moyen', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('paypal', 'PayPal')], default='mobile_money', max_length=20)),
                ('partage_identite', models.BooleanField(default=False, help_text="Le donateur accepte que son nom et son email soient transmis à l'ONG")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('echoue', 'Non abouti')], default='en_attente', max_length=20)),
                ('paye_le', models.DateTimeField(blank=True, null=True)),
                ('recu_envoye', models.BooleanField(default=False, help_text='Confirmation du don envoyée au donateur')),
                ('reversement_notifie', models.BooleanField(default=False, help_text="Donateur prévenu du reversement à l'ONG")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dons', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dons', to='give.organisationmodel')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='give.projetmodel')),
                ('reversement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='give.reversementmodel')),
            ],
            options={
                'verbose_name': 'Don',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='reversementmodel',
            constraint=models.UniqueConstraint(fields=('organisation', 'periode'), name='reversement_unique_par_mois'),
        ),
    ]
