# Generated by Django 5.1.15 on 2026-10-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='annule_par',
            field=models.CharField(blank=True, choices=[('voyageur', 'Voyageur'), ('hote', 'Hôte'), ('plateforme', 'AfriStay'), ('expiration', 'Paiement non effectué à temps')], max_length=20),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='commission_hote',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='expire_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='frais_service',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='prix_nuits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='confirmed', max_length=20),
        ),
    ]
