# Generated by Django 5.1.15 on 2026-10-07 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_reservationmodel_annule_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField()),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('prestataire', models.CharField(choices=[('fedapay', 'FedaPay (Mobile Money, carte)'), ('paypal', 'PayPal')], default='fedapay', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('montant_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capture_id', models.CharField(blank=True, max_length=64)),
                ('url_paiement', models.URLField(blank=True, max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('mode', models.CharField(blank=True, max_length=40)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('pays_telephone', models.CharField(blank=True, max_length=2)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='reservations.reservationmodel')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ProfilVersementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(choices=[('TG', 'Togo'), ('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('NE', 'Niger'), ('ML', 'Mali')], max_length=2)),
                ('operateur', models.CharField(choices=[('moov_tg', 'Moov Money (Flooz)'), ('togocel', 'Mixx by Yas (T-Money)'), ('mtn_open', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('sbin', 'Celtiis Cash'), ('orange_bf', 'Orange Money'), ('moov_bf', 'Moov Money'), ('airtel_ne', 'Airtel Money'), ('orange_ml', 'Orange Money'), ('moov_ml', 'Moov Money')], max_length=30)),
                ('numero', models.CharField(help_text="Numéro local, sans l'indicatif du pays", max_length=15)),
                ('titulaire', models.CharField(help_text='Nom du titulaire du compte Mobile Money', max_length=120)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('hote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_versement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil de versement',
                'verbose_name_plural': 'Profils de versement',
            },
        ),
        migrations.CreateModel(
            name='RemboursementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField()),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('a_envoyer', 'À envoyer'), ('en_cours', 'En cours'), ('envoye', 'Envoyé'), ('a_traiter', 'À traiter manuellement')], default='a_envoyer', max_length=20)),
                ('payout_id', models.CharField(blank=True, max_length=64)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='paiements.paiementmodel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='reservations.reservationmodel')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='VersementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_brut', models.PositiveIntegerField(help_text="Prix des nuits revenant à l'hôte, avant commission")),
                ('commission', models.PositiveIntegerField()),
                ('montant', models.PositiveIntegerField(help_text="Montant versé à l'hôte")),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('date_prevue', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('envoye', 'Envoyé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('payout_id', models.CharField(blank=True, max_length=64)),
                ('mode', models.CharField(blank=True, max_length=30)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('hote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versements', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='versement', to='reservations.reservationmodel')),
            ],
            options={
                'verbose_name': 'Versement à un hôte',
                'verbose_name_plural': 'Versements aux hôtes',
                'ordering': ['date_prevue'],
            },
        ),
    ]
