# Generated by Django 5.1.15 on 2026-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursementmodel',
            name='numero',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='remboursementmodel',
            name='operateur',
            field=models.CharField(blank=True, choices=[('moov_tg', 'Moov Money (Flooz)'), ('togocel', 'Mixx by Yas (T-Money)'), ('mtn_open', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('sbin', 'Celtiis Cash'), ('orange_bf', 'Orange Money'), ('moov_bf', 'Moov Money'), ('airtel_ne', 'Airtel Money'), ('orange_ml', 'Orange Money'), ('moov_ml', 'Moov Money')], max_length=30),
        ),
        migrations.AddField(
            model_name='remboursementmodel',
            name='pays',
            field=models.CharField(blank=True, choices=[('TG', 'Togo'), ('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('NE', 'Niger'), ('ML', 'Mali')], max_length=2),
        ),
        migrations.AlterField(
            model_name='remboursementmodel',
            name='statut',
            field=models.CharField(choices=[('attente_numero', 'En attente du numéro du voyageur'), ('a_envoyer', 'À envoyer'), ('en_cours', 'En cours'), ('envoye', 'Envoyé'), ('a_traiter', 'À traiter manuellement')], default='a_envoyer', max_length=20),
        ),
    ]
