# Generated by Django 5.1.15 on 2026-10-08 14:18

from django.db import migrations, models


def deja_notifies(apps, schema_editor):
    # Les opérations antérieures à cette migration ne déclenchent pas d'email a posteriori
    apps.get_model('paiements', 'PaiementModel').objects.update(notifie=True, notifie_hote=True)
    for nom in ('VersementModel', 'RemboursementModel'):
        apps.get_model('paiements', nom).objects.update(notifie=True)


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_compte_remboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementmodel',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiementmodel',
            name='notifie_hote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remboursementmodel',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='versementmodel',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(deja_notifies, migrations.RunPython.noop),
    ]
