# Generated by Django 5.1.15 on 2026-10-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_notifications'),
        ('reservations', '0002_reservationmodel_annule_le_and_more'),
        ('transferts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementmodel',
            name='transfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='transferts.transfertmodel'),
        ),
        migrations.AddField(
            model_name='remboursementmodel',
            name='transfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='transferts.transfertmodel'),
        ),
        migrations.AlterField(
            model_name='paiementmodel',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='reservations.reservationmodel'),
        ),
        migrations.AlterField(
            model_name='remboursementmodel',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='reservations.reservationmodel'),
        ),
        migrations.AddConstraint(
            model_name='paiementmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reservation__isnull', False), ('transfert__isnull', True)), models.Q(('reservation__isnull', True), ('transfert__isnull', False)), _connector='OR'), name='paiement_reservation_ou_transfert'),
        ),
    ]
