# Generated by Django 5.1.15 on 2026-10-10 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0001_initial'),
        ('paiements', '0004_paiement_transfert'),
        ('reservations', '0002_reservationmodel_annule_le_and_more'),
        ('transferts', '0002_aeroports_tarifs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paiementmodel',
            name='paiement_reservation_ou_transfert',
        ),
        migrations.AddField(
            model_name='paiementmodel',
            name='don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='give.donmodel'),
        ),
        migrations.AddConstraint(
            model_name='paiementmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('don__isnull', True), ('reservation__isnull', False), ('transfert__isnull', True)), models.Q(('don__isnull', True), ('reservation__isnull', True), ('transfert__isnull', False)), models.Q(('don__isnull', False), ('reservation__isnull', True), ('transfert__isnull', True)), _connector='OR'), name='paiement_reservation_transfert_ou_don'),
        ),
    ]
