# Generated by Django 5.1.15 on 2026-10-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergementmodel',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hebergementmodel',
            name='max_guests',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
