# Generated by Django 5.1.15 on 2026-10-05 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergements', '0003_hebergementphotomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages', to='hebergements.hebergementmodel')),
            ],
            options={
                'ordering': ['debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('debut'))), name='blocage_fin_apres_debut')],
            },
        ),
    ]
