# Generated by Django 5.1.15 on 2026-10-04 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hebergements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_last_read_id', models.BigIntegerField(default=0)),
                ('host_last_read_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_conversations', to=settings.AUTH_USER_MODEL)),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='hebergements.hebergementmodel')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_conversation',
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversationmodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_message',
            },
        ),
        migrations.CreateModel(
            name='NotificationOutboxModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('conversation_id', models.UUIDField()),
                ('message_id', models.BigIntegerField()),
                ('recipient_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'À publier'), ('sent', 'Publiée'), ('skipped', 'Écartée')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('skip_reason', models.CharField(blank=True, max_length=200)),
                ('available_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messaging_notification_outbox',
                'indexes': [models.Index(fields=['status', 'available_at'], name='messaging_outbox_due_idx'), models.Index(fields=['recipient_id', 'status', 'processed_at'], name='messaging_outbox_cap_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversationmodel',
            index=models.Index(fields=['guest', '-last_message_at'], name='messaging_conv_guest_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmodel',
            index=models.Index(fields=['host', '-last_message_at'], name='messaging_conv_host_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmodel',
            constraint=models.UniqueConstraint(fields=('hebergement', 'guest'), name='messaging_unique_hebergement_guest'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['conversation', 'id'], name='messaging_msg_conv_id_idx'),
        ),
    ]
