# Generated by Django 5.1.15 on 2026-10-09 13:48

import apps.voyages.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hebergements', '0004_blocagemodel'),
        ('reservations', '0002_reservationmodel_annule_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, max_length=280)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hebergements.hebergementmodel')),
                ('propose_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='VoyageGroupeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('destination', models.CharField(help_text='Ville', max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nb_voyageurs', models.PositiveSmallIntegerField(default=2, help_text='Pour le budget par personne')),
                ('code_invitation', models.CharField(default=apps.voyages.models.nouveau_code, max_length=32, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Informations pratiques partagées (vols, rendez-vous…)')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages_organises', to=settings.AUTH_USER_MODEL)),
                ('proposition_retenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyages.propositionmodel')),
            ],
            options={
                'verbose_name': 'Voyage de groupe',
                'verbose_name_plural': 'Voyages de groupe',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voyages.propositionmodel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voyages.voyagegroupemodel')),
            ],
        ),
        migrations.AddField(
            model_name='propositionmodel',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='voyages.voyagegroupemodel'),
        ),
        migrations.CreateModel(
            name='MembreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejoint_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages_groupe', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='voyages.voyagegroupemodel')),
            ],
            options={
                'ordering': ['rejoint_le'],
            },
        ),
        migrations.CreateModel(
            name='LienReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.reservationmodel')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voyages.voyagegroupemodel')),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='EtapeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField(blank=True, null=True)),
                ('titre', models.CharField(max_length=120)),
                ('lieu', models.CharField(blank=True, max_length=160)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='voyages.voyagegroupemodel')),
            ],
            options={
                'ordering': ['date', models.OrderBy(models.F('heure'), nulls_first=True), 'cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='voyagegroupemodel',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_debut__isnull', True), ('date_fin__gt', models.F('date_debut')), _connector='OR'), name='voyage_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='votemodel',
            constraint=models.UniqueConstraint(fields=('voyage', 'utilisateur'), name='un_vote_par_membre'),
        ),
        migrations.AddConstraint(
            model_name='propositionmodel',
            constraint=models.UniqueConstraint(fields=('voyage', 'hebergement'), name='proposition_unique'),
        ),
        migrations.AddConstraint(
            model_name='membremodel',
            constraint=models.UniqueConstraint(fields=('voyage', 'utilisateur'), name='membre_unique'),
        ),
        migrations.AddConstraint(
            model_name='lienreservationmodel',
            constraint=models.UniqueConstraint(fields=('voyage', 'reservation'), name='reservation_partagee_unique'),
        ),
    ]
